cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'automake'
brew 'boot-clj'
brew 'coreutils'
brew 'emacs'
brew 'findutils'
brew 'gawk'
brew 'git'
brew 'go'
brew 'grc'
brew 'grep'
brew 'highlight'
brew 'leiningen'
brew 'makedepend'
brew 'nmap'
brew 'nvm'
brew 'openssl'
brew 'pcre'
brew 'pkg-config'
brew 'planck'
brew 'readline'
brew 'rlwrap'
brew 'tree'
brew 'vim'
brew 'watchman'
brew 'wget'


cask 'arq'
cask 'brave'
cask 'caffeine'
cask 'cyberduck'
cask 'firefox'
cask 'firefoxdeveloperedition'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'sequel-pro'
cask 'slack'
cask 'the-unarchiver'
